### PR TITLE
added caching values to integration test app.settings

### PR DESCRIPTION
**Pull request by taylorc**
So that tests can run and pass.

### CODE REVIEW

**Comment by ShreyasJejurkar** [comment]
@taylorc I am not able to see what tests you write for cache? 
Only two files are changed in commit!

**Comment by taylorc** [comment]
@MCCshreyas Correct I took your advice regarding you not being quite ready for test as you're still a bit unsure about the implementation. So I thought I'd hold off. I did notice the Integration tests not passing so I fixed that in the meantime. Looking forward to seeing where you end up with your design. I've been contemplating it was well with not much luck.

**Comment by ShreyasJejurkar** [comment]
@taylorc Ok. What I suggest you, you can start implementing tests based on the current implementation, it won't change much, but it might be, based on feedback from the PR discussion on the main repository (https://github.com/jasontaylordev/CleanArchitecture). And also you will get notified about the discussion, so you can track what I might change, and based on that you can tweak the tests.

**Comment by taylorc** [comment]
Covered in other work which includes tests

**Pull request closed without merging**
